# Generated by Django 5.2.5 on 2025-08-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='produto',
            new_name='produto_id',
        ),
    ]
