# Generated by Django 5.2.5 on 2025-08-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
